### ISSUE TITLE
Site malgraph

### ISSUE THREAD

**Issue by ghost** [rr-/malgraph4#154]
![image](https://cloud.githubusercontent.com/assets/29016810/26529456/ce92204a-439e-11e7-97f5-ed6c955e006b.png)

What should I do to fix this error ?

**Comment by rr-** [comment]
I don't know.
https://github.com/rr-/malgraph4/wiki/Hosting-your-own-MALgraph

**Comment by rr-** [comment]
(Also you might be interested in the fork: https://github.com/anime-plus/graph )
